
name: Sentinel-monitor CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main


jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - run: pip install ruff

      - run: ruff check .

  tests:
    needs: lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13"]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: SetUp python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Tests
        run: python -m pytest -v
